name: Build Web

on:
    workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze .
      - run: flutter build web --release

      - name: move app to tools
        run: |
          mv ./build/web ./tools/gh-pages/app
          sed -i '/^\s*<base\s*href=/c\<base href="cb_app/app/">' ./tools/gh-pages/app/index.html

      - name: deploy to gh pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./tools/gh-pages
          force_orphan: true
