name: Build Linux

on:
    workflow_dispatch

jobs:
  build-and-release-linux:
    runs-on: ubuntu-20.04
    # runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version
      - name: Install dependencies
        run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
      - name: Install project dependencies
        run: flutter pub get
      # - name: Generate intermediates
      #   run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Enable linux build
        run: flutter config --enable-linux-desktop
      - name: Build artifacts
        run: flutter build linux --release
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: CbApp-${{github.ref_name}}-linux.zip
          directory: build/linux/x64/release/bundle
      # - name: Linux Release
      #   uses: softprops/action-gh-release@v1
      #   if: startsWith(github.ref, 'refs/tags/')
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     files: build/linux/x64/release/bundle/CbApp-${{github.ref_name}}-linux.zip

      - uses: actions/upload-artifact@v1
        with:
          name: release-linux
          path: build/linux/x64/release/bundle/CbApp-${{github.ref_name}}-linux.zip
