name: Build Linux

on:
    workflow_dispatch

jobs:
  build-and-release-linux:
    runs-on: ubuntu-20.04
    # runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version
      - name: Install dependencies
        run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
      - name: Install project dependencies
        run: flutter pub get
      - name: Enable linux build
        run: flutter config --enable-linux-desktop
      - name: Build artifacts
        run: flutter build linux --obfuscate --split-debug-info=$RUNNER_TEMP --release

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: cb_app-linux.zip
          directory: build/linux/x64/release/bundle

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: "latest"
          prerelease: true
          file: build/linux/x64/release/bundle/cb_app-linux.zip
          overwrite: true
          body: "Preview binaries for testinstall"

