name: Build Windows

on:
    workflow_dispatch

jobs:
  build-and-release-windows:
    runs-on: windows-latest
    # runs-on: ubuntu-latest

    steps:

      - name: download and move redist
        run: |
          Invoke-WebRequest -URI  https://aka.ms/vs/17/release/vc_redist.x64.exe -OutFile VC_redist.x64.exe
          move VC_redist.x64.exe build\windows\x64\runner\Release\VC_redist.x64.exe


      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version

      - name: Install project dependencies
        run: flutter pub get --suppress-analytics

      - name: Build artifacts
        run: flutter build windows --release --suppress-analytics

    #   - name: download redist
    #     uses: engineerd/configurator@v0.0.9
    #     with:
    #       name: "VC_redist.x64.exe"
    #       url: "https://aka.ms/vs/17/release/vc_redist.x64.exe"

    #   - name: move redist
    #     run: |
    #         dir
    #         move VC_redist.x64.exe build\windows\x64\runner\Release\VC_redist.x64.exe

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: cb_app-windows.zip
          directory: build\windows\x64\runner\Release

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: "latest"
          prerelease: true
          file: build\windows\x64\runner\Release\cb_app-windows.zip
          overwrite: true
          body: "Preview binaries for testinstall"

